export type AIRequest = { system: string; user: string; model?: string; temperature?: number; agentId?: string };
export type AIResponse = { text: string; provider: string; model: string; usage: Record<string, number> };
export interface AIProvider { complete(input: AIRequest): Promise<AIResponse>; }

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const groqKeys=(agent?:string)=>{const id=(agent||'IDSANNA').toUpperCase();const names=[`GROQ_API_KEY_${id}`,id==='IDSANNA'?'GROQ_API_KEY_IDSANNA':'GROQ_API_KEY_IDSANNA','GROQ_API_KEY'];return [...new Set(names)].map(n=>({name:n,key:Deno.env.get(n)})).filter(x=>x.key) as {name:string,key:string}[]};
class GroqProvider implements AIProvider { async complete(input:AIRequest){const keys=groqKeys(input.agentId);if(!keys.length)throw Error('groq_not_configured');const model=input.model||Deno.env.get('GROQ_MODEL')||'openai/gpt-oss-20b';let last='groq_request_failed';for(const k of keys){for(let attempt=0;attempt<2;attempt++){const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${k.key}`},body:JSON.stringify({model,messages:[{role:'system',content:input.system},{role:'user',content:input.user}],temperature:input.temperature??.2})});const d=await r.json().catch(()=>({}));if(r.ok){const text=d.choices?.[0]?.message?.content?.trim();if(text)return {text,provider:'groq',model,usage:d.usage||{}};last='groq_empty_response';break}last=d.error?.code||'groq_request_failed';if(r.status===429||r.status>=500){await sleep(250*(attempt+1));continue}break;}}throw Error(last)} }
class GeminiProvider implements AIProvider { async complete(input:AIRequest){const key=Deno.env.get('GEMINI_API_KEY');if(!key)throw Error('gemini_not_configured');const model=input.model||Deno.env.get('GEMINI_MODEL')||'gemini-2.0-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:input.system}]},contents:[{role:'user',parts:[{text:input.user}]}],generationConfig:{temperature:input.temperature??.2}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error('provider_request_failed');const text=d?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||'').join('').trim();if(!text)throw Error('provider_empty_response');return {text,provider:'gemini',model,usage:d?.usageMetadata||{}}} }
export function configuredProvider(agentId?:string): AIProvider|null { return groqKeys(agentId).length?new GroqProvider():Deno.env.get('GEMINI_API_KEY')?new GeminiProvider():null; }
