-- Learning runtime extension. Idempotent and non-destructive.
create table if not exists public.study_groups (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table if not exists public.memories (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, agent_id text not null, content text not null, importance smallint not null default 1 check(importance between 1 and 5), created_at timestamptz not null default now());
create table if not exists public.evaluations (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, document_id uuid references public.documents(id) on delete set null, score smallint check(score between 1 and 20), rubric jsonb not null default '{}'::jsonb, feedback text, created_at timestamptz not null default now());
create table if not exists public.metadata_schemas (id uuid primary key default gen_random_uuid(), owner_id uuid references auth.users(id) on delete cascade, scope text not null default 'subject', name text not null, version integer not null default 1, definition jsonb not null, enabled boolean not null default true, created_at timestamptz not null default now(), unique(owner_id,name,version));
alter table public.study_groups enable row level security; alter table public.memories enable row level security; alter table public.evaluations enable row level security; alter table public.metadata_schemas enable row level security;
drop policy if exists study_groups_owner on public.study_groups; create policy study_groups_owner on public.study_groups for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists memories_owner on public.memories; create policy memories_owner on public.memories for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists evaluations_owner on public.evaluations; create policy evaluations_owner on public.evaluations for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists metadata_owner on public.metadata_schemas; create policy metadata_owner on public.metadata_schemas for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
