-- Metadata is the versioned source of truth for generated UX and workflows.
-- Non-destructive: creates missing primitives without removing existing data.
create table if not exists public.metadata_fields (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, key text not null, label text not null, data_type text not null, required boolean not null default false, config jsonb not null default '{}'::jsonb, position integer not null default 0, created_at timestamptz not null default now(), unique(schema_id,key));
create table if not exists public.metadata_rules (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, name text not null, rule_type text not null, expression jsonb not null default '{}'::jsonb, severity text not null default 'error', enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.metadata_tags (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, name text not null, color text, config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(schema_id,name));
create table if not exists public.metadata_views (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, name text not null, view_type text not null default 'list', definition jsonb not null default '{}'::jsonb, enabled boolean not null default true, created_at timestamptz not null default now(), unique(schema_id,name));
create table if not exists public.metadata_workflows (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, name text not null, trigger_config jsonb not null default '{}'::jsonb, steps jsonb not null default '[]'::jsonb, enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.metadata_versions (id uuid primary key default gen_random_uuid(), schema_id uuid not null references public.metadata_schemas(id) on delete cascade, version integer not null, snapshot jsonb not null, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), unique(schema_id,version));
create table if not exists public.metadata_events (id uuid primary key default gen_random_uuid(), schema_id uuid references public.metadata_schemas(id) on delete set null, user_id uuid references auth.users(id) on delete set null, event_type text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists metadata_fields_schema_idx on public.metadata_fields(schema_id);
create index if not exists metadata_events_schema_time_idx on public.metadata_events(schema_id,created_at desc);

-- All metadata child rows inherit ownership from metadata_schemas through the schema_id relationship.
-- RLS remains enabled on every table; access is limited to schemas owned by the current user.
do $$ declare t text; begin foreach t in array array['metadata_fields','metadata_rules','metadata_tags','metadata_views','metadata_workflows','metadata_versions','metadata_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
drop policy if exists metadata_fields_owner on public.metadata_fields; create policy metadata_fields_owner on public.metadata_fields for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_rules_owner on public.metadata_rules; create policy metadata_rules_owner on public.metadata_rules for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_tags_owner on public.metadata_tags; create policy metadata_tags_owner on public.metadata_tags for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_views_owner on public.metadata_views; create policy metadata_views_owner on public.metadata_views for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_workflows_owner on public.metadata_workflows; create policy metadata_workflows_owner on public.metadata_workflows for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_versions_owner on public.metadata_versions; create policy metadata_versions_owner on public.metadata_versions for all using (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
drop policy if exists metadata_events_owner on public.metadata_events; create policy metadata_events_owner on public.metadata_events for all using (user_id=auth.uid() or exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid())) with check (user_id=auth.uid() or exists(select 1 from public.metadata_schemas s where s.id=schema_id and s.owner_id=auth.uid()));
